loki-stack:
  loki:
    enabled: true

  promtail:
    enabled: true
    config:
      clients:
        - url: http://monitoring-logging-loki:3100/loki/api/v1/push

  grafana:
    enabled: true

    ingress:
      enabled: true

      ingressClassName: nginx

      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod

      hosts:
        - grafana.docampo-it.ch

      tls:
        - secretName: grafana-k8s-tls
          hosts:
            - grafana.docampo-it.ch

  prometheus:
    enabled: true

    alertmanager:
      enabled: false