loki-stack:
  loki:
    enabled: true

  promtail:
    enabled: true
    config:
      clients:
        - url: http://monitoring-logging-loki:3100/loki/api/v1/push

  grafana:
    enabled: true

    configs:
      cm:
        dex.config: |
          connectors:
            # GitHub example
            - type: github
              id: github
              name: GitHub
              config:
                clientID: aabbccddeeff00112233
                clientSecret: $dex.github.clientSecret # Alternatively $<some_K8S_secret>:dex.github.clientSecret
                orgs:
                - name: your-github-org

    ingress:
      enabled: true

      ingressClassName: nginx

      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod

      hosts:
        - grafana.docampo-it.ch

      tls:
        - secretName: grafana-k8s-tls
          hosts:
            - grafana.docampo-it.ch

  prometheus:
    enabled: true

    alertmanager:
      enabled: false