apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: customer-eigengrau-example-secret
    namespace: customer-eigengrau
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:UygtMzAjSQA/00hs2ccuFIqZ1SlIsuBkS4cG00/AJld9,iv:l64QNjOhx1EvMsaxTKrFMQF/xP/x3InXgn7e6NsesU4=,tag:L3EPXZdrqb5ZtGSpW9t91g==,type:str]
          stringData:
            secretToSuccess: ENC[AES256_GCM,data:2RUXeS2H0pw1ucW99g==,iv:XROoik3atU024jXMU9t6pbW6A7NF/LUAKHFdXDsLl2M=,tag:4b2JC4PtSVAQxTjAf88/sA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z9zl3qm46rlkg2c2fdzytgx7x3gt7mc9flvlcr2j0u2lm264v5aqyqmvyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVnVZOHVLbzl2M29xWGNQ
            TjVEQVlDMW1ZZVluWnFMUStJUSs5VytKZ0RVCll0cVlrOGRVQWNlNmtRbGxGWEQ2
            eTRXbURteXBaU2loQ0F0KzJjblVsU3cKLS0tIHpNOUxKb3ZWMG14WWEydnhBMXdO
            U2tySmJSNE9nSXdHSTczLzBwelFKSUEK1Kte/h2hm0J76JxDQnDaZI0WmFyKxE6e
            a7sYqgaBVHUDghsBmxZrWbR2Lh34qBqnbH5nq5c84d7qWnYiXRITMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-19T20:19:00Z"
    mac: ENC[AES256_GCM,data:WC4QjnlBIdYPyfBqZw/rTNA4H+fsQ4rNXESiwgaGdR/ReUd7o8H3eYG1APYZ4SPleKM/KbXuFK7ew1JaThBkVSpCzp8/14i8qhkVFtuUxkpxT0P9ceoPbJAIRUqKafkVANl1Av2/nBYE72h3m8HntofNtlhncBQylfZ1Ylmqlbg=,iv:q9pk5tCccFab98Su4y0UDYWsqpp07cL2qJVPV5VK4Uo=,tag:9/CvBa7hkPbZaZd4/ZZo0Q==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.7.3
