argo-cd:

  repositories:
    kube-helm-charts:
      url: https://github.com/argoproj/private-repo
    test-repo:
      url: https://github.com/test/kube-helm-charts.git


  server:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      ingressClassName: "nginx"
      hosts:
        - argocd.docampo-it.ch

      paths:
        - /
      pathType: Prefix

      tls:
        - secretName: argocd-k8s-tls
          hosts:
            - argocd.docampo-it.ch