apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
spec:
  syncPolicy:
    automated:
      selfHeal: true
  project: infrastructure 
  source:
    repoURL: https://github.com/sayheyd/kube-helm-charts.git
    targetRevision: main
    path: infrastructure
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd