apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argocd-repo-credentials
    namespace: argocd
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:lzqsrEzQ5Wlu5QzGhGrQ4w==,iv:0u8cak/KTVczhSFNEg6y4Aji/tO50pry8gK6NUn1Jtw=,tag:WbS3ud+k+lrJrdBKw5E3AQ==,type:str]
          stringData:
            url: ENC[AES256_GCM,data:A+GIFHZcQNAPDnFrKTWqT87PQz6SH1FJAPoWxSPteuLOmetUh1jGTXDYAHI44rc=,iv:sduMZcxixn458Jyy7FwvqhFGbHj/pdLsjEvL04r9STg=,tag:X6mYuu7IJ1q/U3e965uDCg==,type:str]
            gh_username: ENC[AES256_GCM,data:jU/7ZoGb8w==,iv:RMw1A6h7mrWKfiNh62wq5nBhGpk4gBqqfRgF/d+p2Cg=,tag:9N7BPKT+NqvGdfiHj1sVYA==,type:str]
            gh_token: ENC[AES256_GCM,data:ERtZlnmbZP06SzrSj9oG9EIGj/MPhHrByDJQIC7kcWfPftrWTngvLnNblJ17jc30QIw3luM4CFcKf7NnGkP32unEl/ySIhBLVcjjqu9jCHT2oJuJKzClaLLXLRy9,iv:Lfg5xdBzjgKlY/j+dgbCtK812RGo8F8LS7qv1qj7SR4=,tag:k+mr2BnTuIl6+pZ2LAY5bg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z9zl3qm46rlkg2c2fdzytgx7x3gt7mc9flvlcr2j0u2lm264v5aqyqmvyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5SDFTRytHbmQ1c25Bd0J3
            TzF3MC9YVU5Xenl4WkRTYVhzYkhQNnRrM1gwCnh5M3g2V3hCLytyVUVNUytsSFVD
            T1FrL0JIc0NFM1pQUUxGanJFQmd4a3MKLS0tIHNpUUlLTHptNzMyUWR6WXF4WXZP
            S3V3cjZ2bUhVRHRyMUttampDVVdXOWMKyw4QV3GBFhRNDw7zNmlp+e+iqKb1ioYp
            /Usj1iZFThdEszsw3QosBtE3U9WCP56Kdu8V6IE34dD9vasqY/KkMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-19T18:52:00Z"
    mac: ENC[AES256_GCM,data:Btcrwo7zeJsV4FRg5RGPdGfQCJboQFKi6wi3ii1Lj+kVsGf7+Xeo/2qRpYTZymYSUe/LI2gkiVHQmg2Y2bMcC5AzqzpIulxWOKR6QZi+HDRp9e5QIDvDVHaRQACjhiFKSfP2NJ+zkCqwpe0oxH/edd08jabdewuXXYAGuhHeNYY=,iv:6ygyhlhr2+cjcL+/nZxdXPl5t8iUkA+MiQMj9pI9kbw=,tag:3hODJ9dsn5ZfDPKpTL/Uqg==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.7.3
