# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: argocd
#   namespace: argocd
# spec:
#   syncPolicy:
#     automated:
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
#   project: default 
#   source:
#     repoURL: https://github.com/sayheyd/kube-helm-charts.git
#     targetRevision: main
#     path: infrastructure/charts/argocd
#     helm:
#       releaseName: argocd
#       valueFiles:
#         - values.yaml
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: argocd