apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: tescht
    namespace: sops
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:xfsQJXoM,iv:yJHJzztrX7+dyU+Kwfm2AEdKvPU7ZHksltNPAiYhvis=,tag:JJpkHX7vHdMbsEiDLuoupA==,type:str]
          data:
            gh_username: ENC[AES256_GCM,data:XkYFqw==,iv:4derj8opP3hb1/VSHAkAQ6yOONrnLwG/s4fQBnca0Oc=,tag:rGxnqf1/pnSu/2er8BgdTA==,type:str]
            gh_token: ENC[AES256_GCM,data:l4p/DhPP,iv:/5wHaWgHhu3fJuuEgfRFdkn+7R1UVZw2ZXJd6lUnrTs=,tag:0ZiabE5QwR8Ut9gzf0T0kA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-01-19T16:51:45Z"
    mac: ENC[AES256_GCM,data:TkM3PxDt1hkcFPAXmqc/9/Jfb0ev4YPUuPXvWHRN/X3R6Eu68lwj5TNirTDx9zpv5n4vRpkBtG7twY9iIAj8FqHDqingPkS6mBmk3l+5GyOFMYwUeRHTGqyFRSqDEQSPbv4MNuzDOjzoPC2mauWfRRpVoy8kjLKZM14H8V7xvsw=,iv:DGGUtpS4+2q5C+k2GdA8+uCdggg1NXtb609OLVzWOuI=,tag:husAD47OmZZ5q0WwtvOWOw==,type:str]
    pgp:
        - created_at: "2023-01-19T16:51:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DJzmPowI6HesSAQdAP+HDk+cUuBFFlgGB8n09ckNmIfApdKFv/9CIIrD/8l0w
            STEvX4n14jbs5plvxTCib4Y8FV7E1VeUU9rO0h87yyFYL09FmL6jWydMYYRECyhk
            1GYBCQIQrQbaGyIWCGKXjqaFfCinaq2AWdP4qvI5XC1bi6UfKp75cDs8x4vLD1v4
            jzn3/zyhLi0DRjYdw3ddKfLDbkA6ku2m3qcnsvX+BYxwowRKc854rbQpOmZxXc14
            iH00WQd7Qio=
            =GSQl
            -----END PGP MESSAGE-----
          fp: FAE93E118390C35266407B53DB7089F3A3F2F957
    encrypted_suffix: Templates
    version: 3.7.3
