apiVersion: ENC[AES256_GCM,data:S3Xy0uF69lLi2Daz5xl4i/pc06LN/HA/gm+E,iv:8l0ZgxQkClym6fJ3qUmUV/rdb3O8StcUPf0Jf++U/ow=,tag:oP0cHMXdn3tMw4dR8ZdfyA==,type:str]
kind: ENC[AES256_GCM,data:8dfTVZa2xgMsuA==,iv:AYnXU04KN3PYDC8If4+g0QdA47qEFOf39CbKzBWeyLs=,tag:eKn7C0FVWmip15y9YiCXHA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:IbeuXOCQXiChFkvf2MgcBN3ncjSgg6q6KNEtlRL2Zpw=,iv:zyxYw5nzMaVejmu974+QNWvCenLTGjt10kuR2en/A4s=,tag:zliQIc4UxHHXadNWKTjFgw==,type:str]
    namespace: ENC[AES256_GCM,data:GTeOajS/JZhb+xGphrj7WE8=,iv:tH4d71gWi084xCp5NSVFJgBTuc0cE3m6nWs5rE+U23k=,tag:NzS4rejGI+oenu7n31cUfw==,type:str]
spec:
    #ENC[AES256_GCM,data:M1g3hJlv0q0MVOXP0Qb3ollCzoStkYuCMRjeyg1DuG6Kqs+yh93kAN2Lp3pMh7nO9g==,iv:flvu7+BWGJjBdr4ePGZR0UcxQV3a8ihXoUGhrcXQ44k=,tag:1QsFBJEKklQeaimZv/eM9w==,type:comment]
    suspend: ENC[AES256_GCM,data:HskGHx0=,iv:+e3L6jHMjmw03Nup6JLS9gTHBQiO8XFQJJq3i+1U4Cw=,tag:hJ3C3f5veflLcxoLS3ylpQ==,type:bool]
    secretTemplates:
        - name: ENC[AES256_GCM,data:FInOZbQnlhzb+TbazG3dOegUAW2eGLBLFhyzNomfIxA=,iv:wYcUyNwH6K2sb6DJrp9LglpLoSjeZvQ5xZn8AxIAnGA=,tag:vCz6EvonRtJPwGViRBj1oQ==,type:str]
          stringData:
            postgres-password: ENC[AES256_GCM,data:OpecAEGPcDMr9Qth6QKOlJZtUVUGWq8o,iv:WQTISZ5QM+2s08Q/NASLcMou3GLbYl5vRQkjhEh2bCg=,tag:l6cbrXoSdbrsdpYNGHrQHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z9zl3qm46rlkg2c2fdzytgx7x3gt7mc9flvlcr2j0u2lm264v5aqyqmvyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTkRhWHVxdi92YlY4YTJX
            dnBHSWhPRlZCdE5IT3hMMGFKaWtUWmVxeVNZCmo1MGFzUHJVZ1M0NkZtQ3BTeWdV
            cW05bzFVUmJVcmtmVEV1NWZlL3Y1T2cKLS0tIFZBV293VXZVK3VBbVlEL0d0bHBD
            V2h1Y09MQjVKTXBCY1FoeGtNSjNBa28K9wJlHyL2ZOIiZ/HKbt5wYt/y+7w5N9KB
            yEVP7ssSb4lfUyBrlB0g1BFeRgtDUoURlBan/lxVEANQoiAQwdftSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-20T09:20:11Z"
    mac: ENC[AES256_GCM,data:JQUNh+VS6MyDPKjTUxtCyGtTeMzq/oR+nkjLL9f9UDwbJEKrntyYLseGAROGa07AKlsQxjPJ2N1jfAmPdWGnIknubPukA10SGihMXlI9W2EuimmyvusOK5B1yB4D0yCUC23v1+uzlCtxKqeoP81w+yEBT1tcLlrYDAicpP7PID4=,iv:sFtyLRD26G/JDlpmmKcjS2U4DOI3FRN9q0PMi0PnnSc=,tag:M+1QYFhx6y3v00TcWNgCUQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
